const ERROR_TYPES = require('../types/telegram');

module.exports = {
  DO_NOT_REPLY: [
    ERROR_TYPES.TOO_MANY_REQUESTS,
    ERROR_TYPES.USER_NOT_FOUND,
    ERROR_TYPES.CHAT_NOT_FOUND,
    ERROR_TYPES.BLOCKED_BY_USER,
    ERROR_TYPES.KICKED_FROM_GROUP,
    ERROR_TYPES.KICKED_FROM_SUPERGROUP,
    ERROR_TYPES.KICKED_FROM_CHANNEL,
    ERROR_TYPES.USER_DEACTIVATED,
    ERROR_TYPES.GROUP_DEACTIVATED,
    ERROR_TYPES.CANNOT_INITIATE_CONVERSATION_WITH_USER,
    ERROR_TYPES.NOT_GROUP_MEMBER,
    ERROR_TYPES.NOT_SUPERGROUP_MEMBER,
    ERROR_TYPES.NOT_CHANNEL_MEMBER,
  ],
};
